/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SapiRecognizer */

#ifndef _Included_SapiRecognizer
#define _Included_SapiRecognizer
#ifdef __cplusplus
extern "C" {
#endif
#undef SapiRecognizer_CLEAR_ALL_STATE
#define SapiRecognizer_CLEAR_ALL_STATE -1i64
#ifdef __cplusplus
}
#endif
#endif
