/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer */

#ifndef _Included_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
#define _Included_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_CLEAR_ALL_STATE
#define org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_CLEAR_ALL_STATE -1i64
/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    getBuiltInGrammars
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_getBuiltInGrammars
  (JNIEnv *, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    Allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_Allocate
  (JNIEnv *, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    Deallocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_Deallocate
  (JNIEnv *, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    Pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_Pause__
  (JNIEnv *, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    Pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_Pause__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    Resume
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_Resume
  (JNIEnv *, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    setGrammars
 * Signature: (Ljava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_setGrammars
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer
 * Method:    getChangeRequestListener
 * Signature: ()Lorg/jvoicexml/jsapi2/EnginePropertyChangeRequestListener;
 */
JNIEXPORT jobject JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_SapiRecognizer_getChangeRequestListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
