/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jvoicexml_jsapi2_sapi_recognition_JNITest */

#ifndef _Included_org_jvoicexml_jsapi2_sapi_recognition_JNITest
#define _Included_org_jvoicexml_jsapi2_sapi_recognition_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jvoicexml_jsapi2_sapi_recognition_JNITest
 * Method:    number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jvoicexml_jsapi2_sapi_recognition_JNITest_number
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
